# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_x_y": "00_utils.ipynb",
         "say_hello_ingestion": "01_ingestion.ipynb",
         "say_hello_EDA": "02_EDA.ipynb"}

modules = ["utils.py",
           "ingestion.py",
           "EDA.py"]

doc_url = "https://ashish-ram.github.io/hello_nbdev/"

git_url = "https://github.com/ashish-ram/hello_nbdev/tree/master/"

def custom_doc_links(name): return None
