# AUTOGENERATED! DO NOT EDIT! File to edit: 02_EDA.ipynb (unless otherwise specified).

__all__ = ['say_hello_EDA']

# Cell
def say_hello_EDA(to):
    """
    this method will say hello to the person named 'to'
    params:
    ======
    to: str, name of the person to which greetings is made
    return: 1 on success
    """
    #print('hello there {}'.format(to))
    return 'hello there {} - EDA'.format(to)