# AUTOGENERATED! DO NOT EDIT! File to edit: 01_ingestion.ipynb (unless otherwise specified).

__all__ = ['say_hello_ingestion']

# Cell
def say_hello_ingestion(to):
    """
    this method will say hello to the person named 'to'
    params:
    ======
    to: str, name of the person to which greetings is made
    return: 1 on success
    """
    #print('hello there {}'.format(to))
    return 'hello there {} - ingestion'.format(to)