# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['plot_x_y']

# Cell
from matplotlib import pyplot as plt

# Cell
def plot_x_y(x,y):
    """
    this method will plt x and y
    """
    plt.plot(x,y)